name: Crowdin Translations

# FIXME: Remove `crowdin-action` branch
on:
  push:
    branches: [main, crowdin-action]

jobs:
  crowdin:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - uses: actions/checkout@v4
      - uses: crowdin/github-action@v2
        with:
          upload_sources: true
          upload_translations: true
          download_translations: true
          create_pull_request: true
          commit_message: 'feat(localization): New Crowdin translations'
          pull_request_title: 'feat(localization): New Crowdin translations'
          project_id: ${{ vars.CROWDIN_PROJECT_ID }}
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
